version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: horilla_main
      POSTGRES_USER: horilla
      POSTGRES_PASSWORD: horilla
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=horilla_main
      - DB_USER=horilla
      - DB_PASSWORD=horilla
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - media_files:/app/media
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
  media_files:
